### ISSUE TITLE
No more symfony log

### ISSUE THREAD

**Issue by brunonic** [Kwrz/TwigException#1]
Hi, very nice bundle but now, when I got an exception, there is no more log. Then I can't really know what is the problem when it's happen.

**Comment by JulienDemangeon** [comment]
Hi ! Sorry to have taken time to respond, I had not seen your message. I will look into the problem soon.

**Comment by salemgolemugoo** [comment]
You should take a look at the https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/EventListener/ExceptionListener.php (onKernelException method).

**Comment by JulienDemangeon** [comment]
I can't reproduce the same issue in my project, the logging system is always functional. 

Moreover, the event is not stopped and should be covered by the ExceptionListener of Symfony (and the exception logged).

Have you more information or a stack trace ?

In any case, thank you for these returns.
